name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Deploy to DigitalOcean Spaces
        uses: jakejarvis/digitalocean-spaces-sync@v1
        with:
          args: --key ${{ secrets.DO_SPACES_KEY }} --secret ${{ secrets.DO_SPACES_SECRET }} --bucket posters-assets --local-dir . --region nyc3 --remote-dir https://github.com/muhammadwaqasdev/poster-maker-backend
