name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy to DigitalOcean Spaces
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: posters-assets
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # uses: jakejarvis/digitalocean-spaces-sync@v1
        # with:
        #   args: --key ${{ secrets.DO_SPACES_KEY }} --secret ${{ secrets.DO_SPACES_SECRET }} --bucket posters-assets --local-dir . --region nyc3 --remote-dir https://github.com/muhammadwaqasdev/poster-maker-backend
